### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 722 and 697 in dimension 3 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensor.cpp:612

### ISSUE THREAD

**Issue by CatchBeliF** [unique-chan/Complement-Cross-Entropy#1]
Hello, thanks for your work.
When I run the 1_train.py ,there are something wrong in 'for batch_idx, (inputs, targets) in enumerate(valid_loader):'.
Could you please tell us what the data format looks like in your a_dataset.
our dataset is 15000   pictures for train,3000 for valid,there are all have 10 catogories.
We are looking forward for your reply!Thank you very much!

**Comment by unique-chan** [comment]
Dear CatchBelif,

Kindly, read this usage:
https://github.com/unique-chan/Complement-Cross-Entropy/blob/master/a_datasets/README.md

If you have other questions, let me know.

Sincerely,
Yechan Kim


________________________________
보낸 사람: CatchBeliF <notifications@github.com>
보낸 날짜: 2020년 9월 13일 일요일 오후 11:07
받는 사람: unique-chan/Complement-Cross-Entropy <Complement-Cross-Entropy@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
제목: [unique-chan/Complement-Cross-Entropy] RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 722 and 697 in dimension 3 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensor.cpp:612 (#1)


Hello, thanks for your work.
When I run the 1_train.py ,there are something wrong in 'for batch_idx, (inputs, targets) in enumerate(valid_loader):'.
Could you please tell us what the data format looks like in your a_dataset.
our dataset is 15000 pictures for train,3000 for valid,there are all have 10 catogories.
We are looking forward for your reply!Thank you very much!
